name: Draft release

on:
  workflow_call:
    inputs:
      dh_name:
        type: string
        required: true
      deploy_repository:
        type: string
        required: true
      deploy_local_path:
        type: string
        required: true
      product_type:
        type: string
        required: true
      target:
        type: string
        required: false

    secrets:
      tg_token:
        required: true
      tg_chat_id:
        required: true
      dh_token:
        required: true
      deploy_repo_ssh_key:
        required: true
      # dd_sec_url:
      #   required: false
      # dd_sec_key:
      #   required: false

jobs:

  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set docker image name
        run: |
          echo DOCKER_IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          flavor: |
            latest=false
          tags: 
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dh_name }}
          password: ${{ secrets.dh_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            target=${{ inputs.target }}
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Send message on failure
        if: ${{ failure() }}
        uses: yamaks2306/telegram-notification@main
        with:
          token: ${{ secrets.tg_token }}
          chat_id: ${{ secrets.tg_chat_id }}
          include_commit_info: false
          message: '💥💥💥 Job was failed! Repository: ${{ github.repository }}, workflow: ${{ github.workflow }}, Job: ${{ github.job }}'

    outputs:
      docker_tag: ${{ steps.docker_meta.outputs.tags }} 


  update_deploy_repo:
    name: Update deploy repo
    needs:
      - build
    runs-on: ubuntu-latest
    steps:

      - name: Set app name
        run: |
          echo APP_NAME=$(awk -F "/" '{print $2}' <<< ${{ github.repository }}) >> $GITHUB_ENV

      - name: Checkout configs repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.deploy_repository }}
          path: ${{ inputs.deploy_local_path }}
          ssh-key: ${{ secrets.deploy_repo_ssh_key }}

      - name: Update image version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/${{ env.APP_NAME }}/stage-values.yaml'
          propertyPath: 'image.tag'
          value: ${{ needs.build.outputs.docker_tag }}
          repository: ${{ inputs.deploy_repository }}
          workDir: ${{ inputs.deploy_local_path }}
          updateFile: true
          createPR: false
          commitChange: false

      - name: Install helm
        uses: yamaks2306/kube-tools@master
        with:
          helm: 3.7.2

      - name: Lint helm
        run: |
          helm lint ${{ inputs.deploy_local_path }}/helm/${{ env.APP_NAME }} --values ${{ inputs.deploy_local_path }}/helm/${{ env.APP_NAME }}/stage-values.yaml

      - name: Generate manifests with Helm
        run: | 
          helm template stage-${{ env.APP_NAME }} ${{ inputs.deploy_local_path }}/helm/${{ env.APP_NAME }} --values ${{ inputs.deploy_local_path }}/helm/${{ env.APP_NAME }}/stage-values.yaml > ${{ inputs.deploy_local_path }}/apps/${{ env.APP_NAME }}/stage/${{ env.APP_NAME }}.yaml

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'manifest-report.sarif'
          exit-code: '0'
          scan-ref: '${{ inputs.deploy_local_path }}/apps/${{ env.APP_NAME }}/stage/'

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: manifest-report
          path: ./manifest-report.sarif

      - name: Commit and push changes
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.deploy_repo_ssh_key }}'
          cd ${{ inputs.deploy_local_path }}
          git config user.name github-action
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Image version updated ${{ needs.build.outputs.docker_tag }}'
          git push

      - name: Send message on failure
        if: ${{ failure() }}
        uses: yamaks2306/telegram-notification@main
        with:
          token: ${{ secrets.tg_token }}
          chat_id: ${{ secrets.tg_chat_id }}
          include_commit_info: false
          message: '💥💥💥 Job was failed! Repository: ${{ github.repository }}, workflow: ${{ github.workflow }}, Job: ${{ github.job }}'


  draft_release:
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send message on failure
        if: ${{ failure() }}
        uses: yamaks2306/telegram-notification@main
        with:
          token: ${{ secrets.tg_token }}
          chat_id: ${{ secrets.tg_chat_id }}
          include_commit_info: false
          message: '💥💥💥 Job was failed! Repository: ${{ github.repository }}, workflow: ${{ github.workflow }}, Job: ${{ github.job }}'

      - name: Send message on success
        if: ${{ success() }}
        uses: yamaks2306/telegram-notification@main
        with:
          token: ${{ secrets.tg_token }}
          chat_id: ${{ secrets.tg_chat_id }}
          docker_tags: ${{ needs.build.outputs.docker_tag }}
          message: 'The draft release ${{ steps.draft_release.outputs.name }} was created successfully. The staging environments configuration was updated with pre-release image ${{ needs.build.outputs.docker_tag }}'
